name: Test & Build

on: [push, pull_request]

jobs:
  test:
    name: Test MyConverter library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Install project libraries
        run: pio lib --environment native install
      - name: Run Unit Test on MyConverter
        run: pio test --environment native

  build:
    name: Build esp32 binary
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Cache PlatformIO dependencies
        uses: actions/cache@v2
        env:
          cache-name: platformio-deps
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('platformio.ini') }}
      - name: Install Python minifier
        run: pip install css-html-js-minify
      - name: Run PlatformIO
        run: pio run --environment esp32dev
